FROM python:3.13-slim

# Install system deps needed for python-ldap + hybrid verify
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      gcc \
      python3-dev \
      libldap2-dev \
      libsasl2-dev \
      ldap-utils \
    && rm -rf /var/lib/apt/lists/*

# Install your Python deps
RUN pip install flask requests oqs

WORKDIR /app
COPY rp/app /app
COPY rp/app/requirements.txt /app/requirements.txt

# Now python_ldap can build
RUN pip install -r requirements.txt

ENV OPENSSL_MODULES=/usr/lib/x86_64-linux-gnu/ossl-modules

EXPOSE 80
CMD ["python3", "app.py"]
